"""fix MySQL schema

Revision ID: 2c5df41c436f
Revises: 
Create Date: 2025-10-07 18:33:55.258875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c5df41c436f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_donation_requests_id'), table_name='donation_requests')
    op.drop_table('donation_requests')
    op.drop_index(op.f('ix_featured_books_id'), table_name='featured_books')
    op.drop_table('featured_books')
    op.drop_index(op.f('ix_borrowings_id'), table_name='borrowings')
    op.drop_table('borrowings')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_emails_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_admin_settings_id'), table_name='admin_settings')
    op.drop_table('admin_settings')
    op.drop_table('books_backup')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_table('features')
    op.alter_column('bookings', 'booking_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('bookings', 'expected_available_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'FULFILLED', 'CANCELLED', 'EXPIRED', name='bookingstatusenum'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('bookings', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('books', 'format',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('HARD_COPY', 'E_BOOK', 'AUDIO_BOOK', name='bookformatenum'),
               existing_nullable=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.drop_constraint(op.f('books_ibfk_1'), 'books', type_='foreignkey')
    op.alter_column('borrows', 'borrow_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('borrows', 'due_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('borrows', 'return_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('borrows', 'status',
               existing_type=mysql.ENUM('REQUESTED', 'PENDING', 'ACTIVE', 'ACCEPTED', 'REJECTED', 'RETURNED'),
               type_=sa.Enum('REQUESTED', 'ACCEPTED', 'ACTIVE', 'RETURNED', 'OVERDUE', 'REJECTED', name='borrowstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'REQUESTED'"))
    op.alter_column('borrows', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('categories', 'description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('name'), table_name='categories')
    op.drop_index(op.f('name_2'), table_name='categories')
    op.alter_column('reviews', 'comment',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'USER', name='userroleenum'),
               existing_nullable=False)
    op.drop_column('users', 'address')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.DATE(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('address', mysql.VARCHAR(length=500), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', name='userroleenum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('reviews', 'comment',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.create_index(op.f('name_2'), 'categories', ['name'], unique=True)
    op.create_index(op.f('name'), 'categories', ['name'], unique=True)
    op.alter_column('categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('borrows', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('borrows', 'status',
               existing_type=sa.Enum('REQUESTED', 'ACCEPTED', 'ACTIVE', 'RETURNED', 'OVERDUE', 'REJECTED', name='borrowstatus'),
               type_=mysql.ENUM('REQUESTED', 'PENDING', 'ACTIVE', 'ACCEPTED', 'REJECTED', 'RETURNED'),
               existing_nullable=False,
               existing_server_default=sa.text("'REQUESTED'"))
    op.alter_column('borrows', 'return_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('borrows', 'due_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)
    op.alter_column('borrows', 'borrow_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)
    op.create_foreign_key(op.f('books_ibfk_1'), 'books', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.alter_column('books', 'format',
               existing_type=sa.Enum('HARD_COPY', 'E_BOOK', 'AUDIO_BOOK', name='bookformatenum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('bookings', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('PENDING', 'FULFILLED', 'CANCELLED', 'EXPIRED', name='bookingstatusenum'),
               type_=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('bookings', 'expected_available_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)
    op.alter_column('bookings', 'booking_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)
    op.create_table('features',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('max_borrow_duration', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_borrow_limit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_extension_limit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_booking_duration', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_booking_limit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('books_backup',
    sa.Column('id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('cover', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pdf_file', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('audio_file', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('copies_total', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('copies_available', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('average_rating', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('format', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin_settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('borrow_day_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('borrow_extend_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('borrow_book_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('booking_days_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_admin_settings_id'), 'admin_settings', ['id'], unique=False)
    op.create_table('news',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_table('emails',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('body', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('sent_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('emails_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_emails_id'), 'emails', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('pages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_table('borrowings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('take_date', sa.DATE(), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('borrowings_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('borrowings_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_borrowings_id'), 'borrowings', ['id'], unique=False)
    op.create_table('featured_books',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_featured_books_book_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_featured_books_id'), 'featured_books', ['id'], unique=False)
    op.create_table('donation_requests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('admin_notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('donation_requests_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_donation_requests_id'), 'donation_requests', ['id'], unique=False)
    op.create_table('donations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('donation_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('donations_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('donations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    # ### end Alembic commands ###